# Generated by Django 5.1.6 on 2025-05-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_merchattransactionsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UzumBankTransactionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_id', models.BigIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('CONFIRMED', 'CONFIRMED'), ('REVERSED', 'REVERSED')], max_length=11)),
                ('trans_time', models.BigIntegerField(blank=True, null=True)),
                ('confirm_time', models.BigIntegerField(blank=True, null=True)),
                ('reverse_time', models.BigIntegerField(blank=True, null=True)),
                ('payment_source', models.CharField(blank=True, max_length=100, null=True)),
                ('tariff', models.CharField(blank=True, max_length=50, null=True)),
                ('processing_reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
