# Generated by Django 5.1.6 on 2026-03-05 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_remove_fcmtoken_status'),
        ('payment', '0003_uzumbanktransactionsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=255, unique=True)),
                ('pan', models.CharField(blank=True, max_length=255, null=True)),
                ('card_holder', models.CharField(blank=True, max_length=255, null=True)),
                ('expiry', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='authorization.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
