# Generated by Django 5.1.6 on 2026-04-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_customercard'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercard',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
