# Generated by Django 5.1.6 on 2026-04-29 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_customercard_options_customercard_is_default'),
        ('service', '0061_order_ofd_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtmosTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_trans_id', models.BigIntegerField(verbose_name='ID успешной транзакции')),
                ('trans_id', models.BigIntegerField(verbose_name='ID транзакции')),
                ('store_id', models.IntegerField(blank=True, null=True, verbose_name='ID магазина')),
                ('store_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название магазина')),
                ('terminal_id', models.CharField(blank=True, default='', max_length=255, verbose_name='ID терминала')),
                ('account', models.CharField(max_length=255, verbose_name='Аккаунт')),
                ('amount', models.BigIntegerField(verbose_name='Сумма')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('prepay_time', models.BigIntegerField(blank=True, null=True, verbose_name='Время предоплаты')),
                ('confirm_time', models.BigIntegerField(blank=True, null=True, verbose_name='Время подтверждения')),
                ('ofd_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на чек')),
                ('commission_value', models.CharField(blank=True, default='0', max_length=50, verbose_name='Комиссия')),
                ('commission_type', models.CharField(blank=True, default='', max_length=50, verbose_name='Тип комиссии')),
                ('total', models.BigIntegerField(blank=True, null=True, verbose_name='Итого')),
                ('status_code', models.CharField(blank=True, default='', max_length=10, verbose_name='Код статуса')),
                ('status_message', models.CharField(blank=True, default='', max_length=255, verbose_name='Сообщение статуса')),
                ('pc_type', models.CharField(blank=True, default='', max_length=50, verbose_name='Тип платежной системы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atmos_transactions', to='service.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Транзакция Atmos',
                'verbose_name_plural': 'Транзакции Atmos',
                'ordering': ['-created_at'],
            },
        ),
    ]
