# Generated by Django 5.1.6 on 2025-04-17 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_customer_latitude_customer_location_name_and_more'),
        ('service', '0006_remove_productcategory_brand_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображение продукта', 'verbose_name_plural': 'Изображения продуктов'},
        ),
        migrations.AddField(
            model_name='product',
            name='in_cart',
            field=models.BooleanField(default=False, verbose_name='в корзине'),
        ),
        migrations.AddField(
            model_name='productcharacteristics',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.product', verbose_name='Продукт'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart_token', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Токен карзины')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Карзина',
                'verbose_name_plural': 'Карзины',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='service.cart', verbose_name='Карзина')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_product', to='service.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Вещь в корзине',
                'verbose_name_plural': 'Вещи в корзине',
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
