# Generated by Django 5.1.6 on 2025-04-20 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_cartitem_is_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcharacteristics',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_characteristics', to='service.product', verbose_name='Продукт'),
        ),
    ]
