# Generated by Django 5.1.6 on 2025-04-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_alter_productcharacteristics_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comments_quantity',
            field=models.IntegerField(default=0, verbose_name='Количество коментариев'),
        ),
    ]
