# Generated by Django 5.1.6 on 2025-04-21 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_comment_is_commented'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_commented',
        ),
    ]
