# Generated by Django 5.1.6 on 2025-04-21 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_remove_comment_is_commented'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_favourite',
        ),
    ]
