# Generated by Django 5.1.6 on 2025-04-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_remove_product_is_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(upload_to='product_category', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productitemcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_category', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sub_category', verbose_name='Изображение'),
        ),
    ]
