# Generated by Django 5.1.6 on 2025-04-22 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_customeraddresses_is_default'),
        ('service', '0018_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourites',
            name='favourite_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Токен карзины'),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.customer', verbose_name='Клиент'),
        ),
    ]
