# Generated by Django 5.1.6 on 2025-04-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='saved_price',
            field=models.FloatField(default=0.0, verbose_name='Сэкономленная сумма'),
        ),
    ]
