# Generated by Django 5.1.6 on 2025-04-25 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_customeraddresses_is_default'),
        ('service', '0027_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyViewedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.customer', verbose_name='Клиент')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Недавно просмотренный продукт',
                'verbose_name_plural': 'Недавно просмотренные продукты',
                'ordering': ('-created_at',),
            },
        ),
    ]
