# Generated by Django 5.1.6 on 2025-04-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0030_rename_product_order_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcharacteristics',
            name='unit',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Еденица измерения'),
        ),
    ]
