# Generated by Django 5.1.6 on 2025-04-28 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_promocodes_expires_at'),
        ('service', '0031_alter_productcharacteristics_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.promocodes', verbose_name='Промокод'),
        ),
    ]
