# Generated by Django 5.1.6 on 2025-05-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0033_sale_image_alter_sale_bg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(related_name='sale_products', to='service.product', verbose_name='Продукты'),
        ),
    ]
