# Generated by Django 5.1.6 on 2025-05-17 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_passwordresettoken'),
        ('service', '0043_alter_commentreply_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreply',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reply', to='service.comment', verbose_name='Коментарий'),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.customer', verbose_name='Клиент'),
        ),
    ]
