# Generated by Django 5.1.6 on 2025-05-29 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_passwordresettoken'),
        ('service', '0050_remove_brand_idx_brand_image_trgm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authorization.customeraddresses', verbose_name='Локация доставки'),
        ),
    ]
