# Generated by Django 5.1.6 on 2025-06-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0051_order_order_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='favourite_token',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Токен карзины'),
        ),
    ]
