# Generated by Django 5.1.6 on 2026-02-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0055_alter_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hold_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Hold'), (2, 'Paid'), (3, 'Cancelled')], default=0, verbose_name='Статус оплаты'),
        ),
    ]
