# Generated by Django 5.1.6 on 2026-03-12 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0056_order_hold_id_order_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('name_uz', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('is_filterable', models.BooleanField(default=True, verbose_name='Фильтруемый')),
                ('position', models.IntegerField(default=0, verbose_name='Позиция')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_attributes', to='service.productitemcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Атрибут категории',
                'verbose_name_plural': 'Атрибуты категорий',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='CategoryAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=150, verbose_name='Значение')),
                ('value_uz', models.CharField(max_length=150, null=True, verbose_name='Значение')),
                ('value_ru', models.CharField(max_length=150, null=True, verbose_name='Значение')),
                ('value_en', models.CharField(max_length=150, null=True, verbose_name='Значение')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='service.categoryattribute', verbose_name='Атрибут')),
            ],
            options={
                'verbose_name': 'Значение атрибута',
                'verbose_name_plural': 'Значения атрибутов',
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.categoryattribute', verbose_name='Атрибут')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.categoryattributevalue', verbose_name='Значение атрибута')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attribute_values', to='service.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Значение атрибута продукта',
                'verbose_name_plural': 'Значения атрибутов продуктов',
                'unique_together': {('product', 'attribute', 'attribute_value')},
            },
        ),
    ]
