# Generated by Django 5.1.6 on 2026-07-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0071_add_payment_type_and_method_to_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                (
                    "name_uz",
                    models.CharField(max_length=50, null=True, verbose_name="Название"),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=50, null=True, verbose_name="Название"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=50, null=True, verbose_name="Название"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Единица измерения",
                "verbose_name_plural": "Единицы измерения",
            },
        ),
    ]
