# Generated by Django 5.1.6 on 2026-07-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0076_update_1c_integration_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="guid",
        ),
        migrations.AddField(
            model_name="brand",
            name="code",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Код из 1С",
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="code",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Код из 1С",
            ),
        ),
        migrations.AddField(
            model_name="productitemcategory",
            name="code",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Код из 1С",
            ),
        ),
        migrations.AddField(
            model_name="productsubcategory",
            name="code",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Код из 1С",
            ),
        ),
        migrations.AddField(
            model_name="productunit",
            name="name_full_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Полное название (англ.)"
            ),
        ),
        migrations.AddField(
            model_name="productunit",
            name="name_full_ru",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Полное название (рус.)"
            ),
        ),
        migrations.AddField(
            model_name="productunit",
            name="name_full_uz",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Полное название (узб.)"
            ),
        ),
        migrations.AddField(
            model_name="productunit",
            name="unit_code",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Код единицы измерения",
            ),
        ),
        migrations.AlterField(
            model_name="productunit",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Краткое название"),
        ),
        migrations.AlterField(
            model_name="productunit",
            name="name_en",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Краткое название"
            ),
        ),
        migrations.AlterField(
            model_name="productunit",
            name="name_ru",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Краткое название"
            ),
        ),
        migrations.AlterField(
            model_name="productunit",
            name="name_uz",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Краткое название"
            ),
        ),
    ]
