# Generated by Django 5.1.6 on 2026-08-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0077_remove_brand_guid_brand_code_productcategory_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_price",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                max_digits=18,
                verbose_name="Стоимость доставки",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="yandex_claim_id",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="ID заявки Яндекс Доставки",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="yandex_claim_status",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Статус заявки Яндекс Доставки",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="Высота, м",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="length",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="Длина, м",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="Вес, кг",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="width",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="Ширина, м",
            ),
        ),
    ]
