# Generated by Django 5.1.6 on 2026-08-11 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0022_marketbranch_code_alter_marketbranch_branch_type_and_more"),
        ("service", "0079_order_pickup_branch"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductRemaining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.FloatField(default=0.0, verbose_name="Остаток")),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_remaining",
                        to="base.marketbranch",
                        verbose_name="Склад",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_remaining",
                        to="service.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Остаток продукта",
                "verbose_name_plural": "Остатки продуктов",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("branch", "product"),
                        name="unique_branch_product_remaining",
                    )
                ],
            },
        ),
    ]
