# Generated by Django 5.2.17 on 2026-09-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0080_productremaining'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Бренд-партнёр',
                'verbose_name_plural': 'Бренды-партнёры',
            },
        ),
    ]
