# Generated by Django 5.2.17 on 2026-09-29 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0083_productcategory_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('name_uz', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('value_type', models.CharField(choices=[('number', 'Число'), ('list', 'Список')], default='list', max_length=20, verbose_name='Тип значения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='service.productitemcategory', verbose_name='Предметная категория')),
            ],
            options={
                'verbose_name': 'Атрибут продукта',
                'verbose_name_plural': 'Атрибуты продуктов',
            },
        ),
    ]
