# Generated by Django 5.2.17 on 2026-09-29 14:45

from django.db import migrations
from django.db.models import Count, Max


def remove_duplicates(apps, schema_editor):
    RecentlyViewedProducts = apps.get_model("service", "RecentlyViewedProducts")
    duplicates = (
        RecentlyViewedProducts.objects.values("customer_id", "product_id")
        .annotate(cnt=Count("id"), keep_id=Max("id"))
        .filter(cnt__gt=1)
    )
    for row in duplicates:
        RecentlyViewedProducts.objects.filter(
            customer_id=row["customer_id"], product_id=row["product_id"]
        ).exclude(id=row["keep_id"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0013_customer_block_last_login'),
        ('service', '0084_productattribute'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='recentlyviewedproducts',
            unique_together={('customer', 'product')},
        ),
    ]
