# Generated by Django 5.2.17 on 2026-09-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0085_recentlyviewedproducts_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='value_type',
            field=models.CharField(choices=[('number', 'Число'), ('range', 'Диапазон'), ('list', 'Список'), ('multi_list', 'Множественный выбор'), ('boolean', 'Да/Нет'), ('color', 'Цвет'), ('text', 'Текст')], default='list', max_length=20, verbose_name='Тип значения'),
        ),
    ]
