# Generated by Django 5.2.17 on 2026-09-30 10:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0086_productattribute_value_type_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderOutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID события')),
                ('event_type', models.CharField(choices=[('order.created', 'Заказ создан'), ('order.collecting', 'Заказ передан в сборку'), ('order.canceled', 'Заказ отменён'), ('order.refunded', 'Возврат средств'), ('order.sync_failed', 'Ошибка синхронизации с 1С')], max_length=32, verbose_name='Тип события')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='pending', max_length=16, verbose_name='Статус')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Количество попыток')),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Следующая попытка')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Последняя ошибка')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='service.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Событие заказа (outbox)',
                'verbose_name_plural': 'События заказов (outbox)',
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='idx_outbox_status_next')],
            },
        ),
    ]
