# Generated by Django 5.2.17 on 2026-09-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0087_orderoutboxevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='erp_active',
            field=models.BooleanField(default=True, verbose_name='Активен в 1С'),
        ),
        migrations.AddField(
            model_name='product',
            name='publish_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('review', 'На проверке'), ('published', 'Опубликован')], default='draft', max_length=16, verbose_name='Статус публикации'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchasable',
            field=models.BooleanField(default=False, verbose_name='Доступен к покупке'),
        ),
    ]
