# Generated by Django 5.2.17 on 2026-10-02 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0089_manager_order_manager_ordercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='is_filterable',
            field=models.BooleanField(default=False, verbose_name='Использовать как фильтр'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='unit',
            field=models.CharField(blank=True, max_length=50, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='item_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.productitemcategory', verbose_name='Предметная категория'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='value_type',
            field=models.CharField(choices=[('number', 'Число'), ('list', 'Список'), ('text', 'Текст'), ('boolean', 'Да/Нет')], default='list', max_length=20, verbose_name='Тип значения'),
        ),
        migrations.CreateModel(
            name='ProductAttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=150, verbose_name='Значение')),
                ('value_uz', models.CharField(max_length=150, null=True, verbose_name='Значение')),
                ('value_ru', models.CharField(max_length=150, null=True, verbose_name='Значение')),
                ('value_en', models.CharField(max_length=150, null=True, verbose_name='Значение')),
                ('position', models.IntegerField(default=0, verbose_name='Позиция')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='service.productattribute', verbose_name='Атрибут')),
            ],
            options={
                'verbose_name': 'Значение атрибута',
                'verbose_name_plural': 'Значения атрибутов',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductItemCategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.IntegerField(default=0, verbose_name='Позиция')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_links', to='service.productattribute', verbose_name='Атрибут')),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_links', to='service.productitemcategory', verbose_name='Предметная категория')),
            ],
            options={
                'verbose_name': 'Атрибут категории',
                'verbose_name_plural': 'Атрибуты категорий',
                'ordering': ('position', 'id'),
                'unique_together': {('item_category', 'attribute')},
            },
        ),
        migrations.AddField(
            model_name='productattribute',
            name='item_categories',
            field=models.ManyToManyField(blank=True, related_name='attributes', through='service.ProductItemCategoryAttribute', to='service.productitemcategory', verbose_name='Предметные категории'),
        ),
    ]
