# Generated by Django 5.2.17 on 2026-10-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0091_attribute_categories_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='item_category',
        ),
    ]
