# Generated by Django 5.2.17 on 2026-10-02 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0092_remove_attribute_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('value_uz', models.CharField(max_length=255, null=True, verbose_name='Значение')),
                ('value_ru', models.CharField(max_length=255, null=True, verbose_name='Значение')),
                ('value_en', models.CharField(max_length=255, null=True, verbose_name='Значение')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_values', to='service.productattribute', verbose_name='Атрибут')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='service.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Значение атрибута продукта',
                'verbose_name_plural': 'Значения атрибутов продуктов',
                'unique_together': {('product', 'attribute')},
            },
        ),
    ]
