# Generated by Django 5.2.17 on 2026-10-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0093_productattributevalue'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='brand',
            name='idx_brand_name_en_trgm',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='idx_product_name_en_trgm',
        ),
        migrations.RemoveIndex(
            model_name='productcategory',
            name='idx_category_name_en_trgm',
        ),
        migrations.RemoveField(
            model_name='addsbrands',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='addsbrands',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='addsbrands',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='productattributeoption',
            name='value_en',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='value_en',
        ),
        migrations.RemoveField(
            model_name='productbadge',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='productcharacteristics',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='productcharacteristics',
            name='unit_en',
        ),
        migrations.RemoveField(
            model_name='productcharacteristics',
            name='value_en',
        ),
        migrations.RemoveField(
            model_name='productitemcategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='productitemcategoryfilterschema',
            name='label_en',
        ),
        migrations.RemoveField(
            model_name='productsubcategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='name_full_en',
        ),
        migrations.RemoveField(
            model_name='productvariantgroup',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='productvariantitem',
            name='display_value_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name_en',
        ),
    ]
