# Generated by Django 5.2.17 on 2026-10-02 11:17

import ckeditor.fields
import ckeditor_uploader.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0094_remove_english_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='addsbrands',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='addsbrands',
            name='name_en',
            field=models.CharField(max_length=450, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='addsbrands',
            name='title_en',
            field=models.CharField(max_length=350, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='value_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='value_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='productbadge',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='productcharacteristics',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='productcharacteristics',
            name='unit_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Еденица измерения'),
        ),
        migrations.AddField(
            model_name='productcharacteristics',
            name='value_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='productitemcategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='productitemcategoryfilterschema',
            name='label_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Краткое название'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='name_full_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Полное название (англ.)'),
        ),
        migrations.AddField(
            model_name='productvariantgroup',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название группы'),
        ),
        migrations.AddField(
            model_name='productvariantitem',
            name='display_value_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Значение (текст)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_en'], name='idx_brand_name_en_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_en'], name='idx_product_name_en_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_en'], name='idx_category_name_en_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
