# Generated by Django 5.2.17 on 2026-10-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0095_restore_english_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productitemcategory',
            options={'ordering': ('position', 'id'), 'verbose_name': 'Предметная категория продуктов', 'verbose_name_plural': 'Предметные категории продуктов'},
        ),
        migrations.AlterModelOptions(
            name='productsubcategory',
            options={'ordering': ('position', 'id'), 'verbose_name': 'Подкатегория продуктов', 'verbose_name_plural': 'Подкатегории продуктов'},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='meta_description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='meta_title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='show_in_app',
            field=models.BooleanField(default=True, verbose_name='Показывать в приложении'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='show_on_site',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(blank=True, db_index=False, max_length=255, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='productitemcategory',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='productitemcategory',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='productitemcategory',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='productitemcategory',
            name='meta_description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='productitemcategory',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='productitemcategory',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='productitemcategory',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='productitemcategory',
            name='meta_title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='productitemcategory',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AddField(
            model_name='productitemcategory',
            name='show_in_app',
            field=models.BooleanField(default=True, verbose_name='Показывать в приложении'),
        ),
        migrations.AddField(
            model_name='productitemcategory',
            name='show_on_site',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.AddField(
            model_name='productitemcategory',
            name='slug',
            field=models.SlugField(blank=True, db_index=False, max_length=255, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='meta_description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='meta_title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='show_in_app',
            field=models.BooleanField(default=True, verbose_name='Показывать в приложении'),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='show_on_site',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='slug',
            field=models.SlugField(blank=True, db_index=False, max_length=255, null=True, verbose_name='Slug'),
        ),
    ]
