# Generated by Django 5.2.17 on 2026-10-02 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0098_brand_description_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbadge',
            name='color',
            field=models.CharField(default='#2563EB', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a HEX color, e.g. #2563EB.')], verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='productbadge',
            name='kind',
            field=models.CharField(choices=[('manual', 'Вручную'), ('auto', 'Автоматически')], default='manual', max_length=10, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='productbadge',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AddField(
            model_name='productbadge',
            name='rule_field',
            field=models.CharField(blank=True, choices=[('discount', 'Скидка, %'), ('created_days', 'Добавлен, дней назад'), ('quantity', 'Остаток, шт'), ('sales_30d', 'Продажи за 30 дней, шт')], max_length=20, null=True, verbose_name='Правило: показатель'),
        ),
        migrations.AddField(
            model_name='productbadge',
            name='rule_operator',
            field=models.CharField(blank=True, choices=[('gt', '>'), ('gte', '≥'), ('lt', '<'), ('lte', '≤'), ('eq', '=')], max_length=3, null=True, verbose_name='Правило: оператор'),
        ),
        migrations.AddField(
            model_name='productbadge',
            name='rule_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Правило: значение'),
        ),
    ]
