# Generated by Django 5.2.17 on 2026-10-08 11:49

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0101_product_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='monthly_plan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='План продаж на месяц'),
        ),
    ]
