# Generated by Django 5.2.17 on 2026-10-08 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0102_manager_monthly_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='monthly_plan',
        ),
    ]
