# Generated by Django 5.2.17 on 2026-10-09 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_notification_publish_and_reads'),
        ('service', '0104_product_image_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='show_on_home',
            field=models.BooleanField(default=False, verbose_name='На главной странице'),
        ),
        migrations.CreateModel(
            name='HomeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('slider', 'Слайдер баннеров'), ('categories', 'Категории'), ('badge_products', 'Подборка по тегу'), ('sale_products', 'Товары распродажи'), ('new_products', 'Новые товары'), ('bestsellers', 'Самые продаваемые товары'), ('all_products', 'Все товары'), ('banner', 'Баннер'), ('brands', 'Бренды'), ('pages', 'Страницы'), ('content', 'Статьи и видео'), ('adds_brands', 'Рекламные блоки')], max_length=20, verbose_name='Тип')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Виден')),
                ('show_on_site', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('show_in_app', models.BooleanField(default=True, verbose_name='Показывать в приложении')),
                ('banner_placement', models.CharField(blank=True, choices=[('site_home', 'Сайт · главный слайдер'), ('app_home', 'Приложение · главный экран'), ('catalog', 'Внутри каталога')], default='', max_length=20, verbose_name='Слайдер: расположение баннеров')),
                ('days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Новые товары: за сколько дней')),
                ('pages', models.JSONField(blank=True, default=list, verbose_name='Страницы')),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_blocks', to='service.productbadge', verbose_name='Тег')),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_blocks', to='base.banner', verbose_name='Баннер')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_blocks', to='service.sale', verbose_name='Распродажа')),
            ],
            options={
                'verbose_name': 'Блок главной страницы',
                'verbose_name_plural': 'Блоки главной страницы',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hide_out_of_stock', models.BooleanField(default=True, verbose_name='Скрывать товары без остатка')),
                ('hide_stale_price', models.BooleanField(default=True, verbose_name='Скрывать товары с устаревшей ценой')),
                ('min_products', models.PositiveIntegerField(default=4, verbose_name='Минимум товаров в блоке')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя публикация')),
                ('published_data', models.JSONField(blank=True, null=True, verbose_name='Опубликованная версия')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Опубликовал')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
    ]
