# Generated by Django 5.2.17 on 2026-10-09 14:41

from django.db import migrations, models


def fill_value_number(apps, schema_editor):
    """Values of `number` attributes entered before the column existed."""
    ProductAttributeValue = apps.get_model("service", "ProductAttributeValue")
    values = []
    for value in ProductAttributeValue.objects.filter(attribute__value_type="number").only("id", "value_ru"):
        try:
            value.value_number = float(value.value_ru)
        except (TypeError, ValueError):
            continue
        values.append(value)
    ProductAttributeValue.objects.bulk_update(values, ["value_number"], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0107_home_page_publish_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributevalue',
            name='value_number',
            field=models.FloatField(blank=True, null=True, verbose_name='Числовое значение'),
        ),
        migrations.AddField(
            model_name='productcharacteristics',
            name='imported_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Перенесено в атрибуты'),
        ),
        migrations.AddField(
            model_name='productitemcategoryattribute',
            name='is_quick_filter',
            field=models.BooleanField(default=False, verbose_name='Быстрый фильтр (чип)'),
        ),
        migrations.AddField(
            model_name='productitemcategoryattribute',
            name='max_quick_filters',
            field=models.PositiveIntegerField(default=0, verbose_name='Макс. кол-во быстрых фильтров'),
        ),
        migrations.RunPython(fill_value_number, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='productattributevalue',
            index=models.Index(fields=['attribute', 'value_ru'], name='idx_attr_value_ru'),
        ),
        migrations.AddIndex(
            model_name='productattributevalue',
            index=models.Index(fields=['attribute', 'value_number'], name='idx_attr_value_number'),
        ),
    ]
