# Generated by Django 5.2.17 on 2026-10-10 11:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0015_staff_profile'),
        ('service', '0108_attribute_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='personal_feed_enabled',
            field=models.BooleanField(default=True, verbose_name='Персональная лента включена'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='personal_feed_holdout_percent',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Персональная лента: контрольная группа, %'),
        ),
        migrations.CreateModel(
            name='FeedImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feed_request_id', models.UUIDField(db_index=True, verbose_name='ID ленты')),
                ('device_id', models.CharField(blank=True, default='', max_length=300, verbose_name='ID устройства')),
                ('seed', models.PositiveIntegerField(verbose_name='Seed')),
                ('page', models.PositiveIntegerField(verbose_name='Страница')),
                ('page_size', models.PositiveIntegerField(verbose_name='Размер страницы')),
                ('variant', models.CharField(choices=[('personal', 'Персональная лента'), ('popular', 'Нет сигналов: популярные + случайные'), ('holdout', 'Контрольная группа: случайная лента'), ('disabled', 'Лента выключена'), ('error', 'Ошибка: случайная лента')], max_length=16, verbose_name='Вариант')),
                ('personalized', models.BooleanField(default=False, verbose_name='Персонализирована')),
                ('items', models.JSONField(blank=True, default=list, verbose_name='Показанные товары')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_impressions', to='authorization.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Показ ленты',
                'verbose_name_plural': 'Показы ленты',
                'indexes': [models.Index(fields=['customer', 'created_at'], name='idx_feedimp_cust_created'), models.Index(fields=['device_id', 'created_at'], name='idx_feedimp_device_created')],
            },
        ),
        migrations.CreateModel(
            name='InterestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('view', 'Просмотр товара'), ('search', 'Поиск')], max_length=10, verbose_name='Тип события')),
                ('device_id', models.CharField(blank=True, default='', max_length=300, verbose_name='ID устройства')),
                ('query', models.CharField(blank=True, default='', max_length=255, verbose_name='Поисковый запрос')),
                ('item_category_ids', models.JSONField(blank=True, default=list, verbose_name='Предметные категории результатов')),
                ('results_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Найдено товаров')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interest_events', to='authorization.customer', verbose_name='Клиент')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interest_events', to='service.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Событие интереса',
                'verbose_name_plural': 'События интереса',
                'indexes': [models.Index(fields=['customer', 'created_at'], name='idx_interest_cust_created'), models.Index(fields=['device_id', 'created_at'], name='idx_interest_device_created')],
            },
        ),
    ]
