# Generated by Django 5.1.6 on 2025-04-21 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_questions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
