# Generated by Django 5.1.6 on 2025-04-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_delete_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Название')),
                ('discount_precent', models.IntegerField(blank=True, null=True, verbose_name='Процент скидки')),
                ('discount_price', models.FloatField(blank=True, null=True, verbose_name='Сумма скидки')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.DeleteModel(
            name='Promocode',
        ),
    ]
