# Generated by Django 5.1.6 on 2025-05-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_banner_image_banner_desktop_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.URLField(default='', verbose_name='Линк'),
            preserve_default=False,
        ),
    ]
