# Generated by Django 5.1.6 on 2025-05-25 19:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_chat_chat_token_alter_chat_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=450, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=450, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=450, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='promocodes',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='promocodes',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='promocodes',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='video',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='video',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='video',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
    ]
