# Generated by Django 5.1.6 on 2026-07-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0019_deletebutton"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Номер телефона"),
                ),
                (
                    "additional_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Дополнительный номер телефона",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Электронная почта"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Адрес"
                    ),
                ),
                (
                    "working_hours",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Рабочее время",
                    ),
                ),
                (
                    "telegram",
                    models.URLField(blank=True, null=True, verbose_name="Telegram"),
                ),
                (
                    "instagram",
                    models.URLField(blank=True, null=True, verbose_name="Instagram"),
                ),
                (
                    "facebook",
                    models.URLField(blank=True, null=True, verbose_name="Facebook"),
                ),
                (
                    "youtube",
                    models.URLField(blank=True, null=True, verbose_name="YouTube"),
                ),
                (
                    "telegram_support",
                    models.URLField(
                        blank=True, null=True, verbose_name="Telegram поддержка"
                    ),
                ),
                (
                    "google_play_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Google Play ссылка"
                    ),
                ),
                (
                    "app_store_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="App Store ссылка"
                    ),
                ),
            ],
            options={
                "verbose_name": "Базовая информация",
                "verbose_name_plural": "Базовая информация",
            },
        ),
    ]
