# Generated by Django 5.1.6 on 2026-08-11 10:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0021_marketbranch"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketbranch",
            name="code",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Код склада из 1С",
            ),
        ),
        migrations.AlterField(
            model_name="marketbranch",
            name="branch_type",
            field=models.IntegerField(
                choices=[(0, "Showroom"), (1, "Market"), (2, "Warehouse")],
                default=1,
                verbose_name="Тип филиала",
            ),
        ),
        migrations.AlterField(
            model_name="marketbranch",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="marketbranch",
            name="description_en",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="marketbranch",
            name="description_ru",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="marketbranch",
            name="description_uz",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="marketbranch",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Широта"),
        ),
        migrations.AlterField(
            model_name="marketbranch",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Долгота"),
        ),
    ]
