# Generated by Django 5.2.17 on 2026-10-02 14:42

import django.utils.timezone
from django.db import migrations, models


LINK_TYPES = {
    "product": "product",
    "productcategory": "category",
    "productsubcategory": "category",
    "productitemcategory": "category",
    "brand": "brand",
}


def fill_existing_banners(apps, schema_editor):
    """Existing banners: shown since they were created, link type from the target, order = creation order."""
    Banner = apps.get_model("base", "Banner")
    banners = list(Banner.objects.select_related("content_type").order_by("id"))
    for position, banner in enumerate(banners, start=1):
        banner.starts_at = banner.created_at
        banner.position = position
        if banner.content_type_id and banner.object_id:
            banner.link_type = LINK_TYPES.get(banner.content_type.model, "url")
    Banner.objects.bulk_update(banners, ["starts_at", "position", "link_type"])


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_marketbranch_code_alter_marketbranch_branch_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('position', 'id'), 'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AddField(
            model_name='banner',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец показа'),
        ),
        migrations.AddField(
            model_name='banner',
            name='link_type',
            field=models.CharField(choices=[('category', 'Категория'), ('product', 'Товар'), ('badge', 'Тег'), ('brand', 'Бренд'), ('page', 'Страница'), ('url', 'Внешний URL')], default='url', max_length=10, verbose_name='Тип ссылки'),
        ),
        migrations.AddField(
            model_name='banner',
            name='page',
            field=models.CharField(blank=True, default='', help_text='Внутренний путь, например /pro', max_length=255, verbose_name='Страница'),
        ),
        migrations.AddField(
            model_name='banner',
            name='placement',
            field=models.CharField(choices=[('site_home', 'Сайт · главный слайдер'), ('app_home', 'Приложение · главный экран'), ('catalog', 'Внутри каталога')], default='site_home', max_length=20, verbose_name='Расположение'),
        ),
        migrations.AddField(
            model_name='banner',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AddField(
            model_name='banner',
            name='show_on_android',
            field=models.BooleanField(default=True, verbose_name='Показывать в Android'),
        ),
        migrations.AddField(
            model_name='banner',
            name='show_on_ios',
            field=models.BooleanField(default=True, verbose_name='Показывать в iOS'),
        ),
        migrations.AddField(
            model_name='banner',
            name='show_on_site',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.AddField(
            model_name='banner',
            name='starts_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало показа'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, default='', verbose_name='Линк'),
        ),
        migrations.RunPython(fill_existing_banners, migrations.RunPython.noop),
    ]
