# Generated by Django 5.2.17 on 2026-10-02 17:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def keep_old_notifications_as_drafts(apps, schema_editor):
    # rows made before the client API existed were never shown to anyone: keep their text in the default
    # language (ru) and leave them as drafts, so they don't pop up as unread for every customer
    Notification = apps.get_model("base", "Notification")
    Notification.objects.update(
        title_ru=models.F("title"), description_ru=models.F("description"),
        publish_at=models.F("created_at"), is_active=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0014_customer_avatar'),
        ('base', '0023_banner_placement_channels_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-publish_at', '-id'), 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AddField(
            model_name='notification',
            name='deeplink',
            field=models.CharField(blank=True, default='', help_text='Экран приложения, например buildex://category/sement', max_length=255, verbose_name='Диплинк'),
        ),
        migrations.AddField(
            model_name='notification',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='notification',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='notification',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='notification',
            name='publish_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время публикации'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.RunPython(keep_old_notifications_as_drafts, migrations.RunPython.noop),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to='authorization.customer', verbose_name='Клиент')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='base.notification', verbose_name='Уведомление')),
            ],
            options={
                'verbose_name': 'Прочитанное уведомление',
                'verbose_name_plural': 'Прочитанные уведомления',
                'constraints': [models.UniqueConstraint(fields=('notification', 'customer'), name='unique_notification_read')],
            },
        ),
    ]
