# Generated by Django 5.1.6 on 2025-03-20 07:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Категория продуктов', 'verbose_name_plural': 'Категории продуктов'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображение продукта', 'verbose_name_plural': ('Изображения продуктов',)},
        ),
        migrations.AlterModelOptions(
            name='productitemcategory',
            options={'verbose_name': 'Предметная категория продуктов', 'verbose_name_plural': 'Предметные категории продуктов'},
        ),
        migrations.AlterModelOptions(
            name='productsubcategory',
            options={'verbose_name': 'Подкатегория продуктов', 'verbose_name_plural': 'Подкатегории продуктов'},
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=9, verbose_name='Код продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_item_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.productitemcategory', verbose_name='Предметная категория продуктов'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(upload_to='product_category', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_image', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='productitemcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productitemcategory',
            name='product_sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.productsubcategory', verbose_name='Подкатегория продукта'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.productcategory', verbose_name='Категория продукта'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('commentator_name', models.CharField(max_length=150, verbose_name='Имя коментатора')),
                ('product_rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг продукта')),
                ('comment', models.TextField(verbose_name='Коментарий')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарии',
            },
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('defendant_name', models.CharField(max_length=150, verbose_name='Имя ответчика')),
                ('reply', models.TextField(verbose_name='Ответ')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.comment', verbose_name='Коментарий')),
            ],
            options={
                'verbose_name': 'Ответ коментарию',
                'verbose_name_plural': 'Ответы коментариям',
            },
        ),
    ]
