# Generated by Django 5.1.6 on 2025-04-14 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('service', '0003_product_idx_product_name_trgm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_favourite',
            field=models.BooleanField(default=False, verbose_name='Избранный'),
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.customer', verbose_name='Клиент')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Избранный',
                'verbose_name_plural': 'Избранные',
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
