# Generated by Django 5.1.6 on 2025-04-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_product_is_favourite_favourites'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favourites',
            unique_together=set(),
        ),
    ]
