# Generated by Django 5.1.6 on 2025-04-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_favourites_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='productitemcategory',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='productsubcategory',
            name='brand',
        ),
    ]
