# Generated by Django 5.1.6 on 2025-04-17 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_productimage_options_product_in_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_cart',
        ),
    ]
