# Generated by Django 5.1.6 on 2025-04-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_remove_product_in_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Collecting'), (2, 'Delivering'), (3, 'Delivered'), (4, 'Canceled')], default=0, verbose_name='Статус'),
        ),
    ]
