# Generated by Django 5.1.6 on 2025-04-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_checked',
            field=models.BooleanField(default=True, verbose_name='Вабран'),
        ),
    ]
