# Generated by Django 5.1.6 on 2025-04-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_product_comments_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitemcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_category/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sub_category/', verbose_name='Изображение'),
        ),
    ]
