# Generated by Django 5.1.6 on 2025-04-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_productitemcategory_image_productsubcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_commented',
            field=models.BooleanField(default=True, verbose_name='Коментирован'),
        ),
    ]
