# Generated by Django 5.1.6 on 2025-04-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_favourites_favourite_token_alter_favourites_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_cart_quantity',
            field=models.IntegerField(default=0, verbose_name='Количество в корзине'),
        ),
    ]
