# Generated by Django 5.1.6 on 2025-04-22 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_product_in_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_cart_quantity',
        ),
    ]
