# Generated by Django 5.1.6 on 2025-04-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_remove_product_in_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(default=0.0, verbose_name='Общая цена'),
        ),
    ]
