# Generated by Django 5.1.6 on 2025-04-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_cart_saved_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products_total_price',
            field=models.FloatField(default=0.0, verbose_name='Общая стоимость продуктов'),
        ),
    ]
