# Generated by Django 5.1.6 on 2025-04-23 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_cart_products_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-created_at',), 'verbose_name': 'Карзина', 'verbose_name_plural': 'Карзины'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ('-created_at',), 'verbose_name': 'Вещь в корзине', 'verbose_name_plural': 'Вещи в корзине'},
        ),
    ]
