# Generated by Django 5.1.6 on 2025-04-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0025_alter_cart_options_alter_cartitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='questions_quantity',
            field=models.IntegerField(default=0, verbose_name='Количество вопросов'),
        ),
    ]
