# Generated by Django 5.1.6 on 2025-04-24 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_promocodes_delete_promocode'),
        ('service', '0026_product_questions_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.promocodes', verbose_name='Промокод'),
        ),
    ]
