# Generated by Django 5.1.6 on 2025-04-26 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0028_recentlyviewedproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentlyviewedproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed_products', to='service.product', verbose_name='Продукт'),
        ),
    ]
