# Generated by Django 5.1.6 on 2025-04-26 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0029_alter_recentlyviewedproducts_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='promocode',
        ),
    ]
