# Generated by Django 5.1.6 on 2025-05-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0032_alter_order_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='image',
            field=models.ImageField(default='', upload_to='sale/image/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='bg_image',
            field=models.ImageField(upload_to='sale/bg_image/', verbose_name='Изображение фона'),
        ),
    ]
