# Generated by Django 5.1.6 on 2025-05-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0036_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='telegram_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Телеграм id'),
        ),
    ]
