# Generated by Django 5.1.6 on 2025-05-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0037_product_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Телеграм id'),
        ),
    ]
