# Generated by Django 5.1.6 on 2025-05-15 17:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0038_alter_product_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Краткое описансе'),
        ),
    ]
