# Generated by Django 5.1.6 on 2025-05-15 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_passwordresettoken'),
        ('service', '0039_product_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='comment/images/', verbose_name='Изображение')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.comment', verbose_name='Коментарий')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Изображение комментария',
                'verbose_name_plural': 'Изображения комментариев',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reply_comment', models.TextField(verbose_name='Коментарий ответа')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Админ')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Виден')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.comment', verbose_name='Коментарий')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Ответ коментария',
                'verbose_name_plural': 'Ответы коментариям',
                'ordering': ('-created_at',),
            },
        ),
    ]
