# Generated by Django 5.1.6 on 2025-05-16 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0040_commentimages_commentreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentimages',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_image', to='service.comment', verbose_name='Коментарий'),
        ),
    ]
