# Generated by Django 5.1.6 on 2025-05-17 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0044_alter_commentreply_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_reply', to='service.questions', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ вопросу',
                'verbose_name_plural': 'Ответы вопросам',
                'ordering': ('-created_at',),
            },
        ),
    ]
