# Generated by Django 5.1.6 on 2025-05-17 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_passwordresettoken'),
        ('service', '0045_questionsreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsreply',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.customer', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='questionsreply',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Админ'),
        ),
        migrations.AddField(
            model_name='questionsreply',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Виден'),
        ),
    ]
