# Generated by Django 5.1.6 on 2025-05-25 19:05

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0046_questionsreply_customer_questionsreply_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addsbrands',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='addsbrands',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='addsbrands',
            name='description_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='addsbrands',
            name='name_en',
            field=models.CharField(max_length=450, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='addsbrands',
            name='name_ru',
            field=models.CharField(max_length=450, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='addsbrands',
            name='name_uz',
            field=models.CharField(max_length=450, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='addsbrands',
            name='title_en',
            field=models.CharField(max_length=350, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='addsbrands',
            name='title_ru',
            field=models.CharField(max_length=350, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='addsbrands',
            name='title_uz',
            field=models.CharField(max_length=350, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='productcharacteristics',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='productcharacteristics',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='productcharacteristics',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='productcharacteristics',
            name='unit_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Еденица измерения'),
        ),
        migrations.AddField(
            model_name='productcharacteristics',
            name='unit_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Еденица измерения'),
        ),
        migrations.AddField(
            model_name='productcharacteristics',
            name='unit_uz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Еденица измерения'),
        ),
        migrations.AddField(
            model_name='productcharacteristics',
            name='value_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='productcharacteristics',
            name='value_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='productcharacteristics',
            name='value_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='productitemcategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='productitemcategory',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='productitemcategory',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
    ]
