# Generated by Django 5.1.6 on 2025-05-28 00:32

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0047_addsbrands_description_en_addsbrands_description_ru_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='brand',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='idx_brand_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_uz'], name='idx_brand_name_uz_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_ru'], name='idx_brand_name_ru_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_en'], name='idx_brand_name_en_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='idx_category_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_uz'], name='idx_category_name_uz_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_ru'], name='idx_category_name_ru_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_en'], name='idx_category_name_en_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
