# Generated by Django 5.1.6 on 2025-05-28 00:53

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0048_brand_idx_brand_name_trgm_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='brand',
            index=django.contrib.postgres.indexes.GinIndex(fields=['image'], name='idx_brand_image_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=django.contrib.postgres.indexes.GinIndex(fields=['image'], name='idx_category_image_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
