# Generated by Django 5.1.6 on 2025-05-28 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0049_brand_idx_brand_image_trgm_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='brand',
            name='idx_brand_image_trgm',
        ),
        migrations.RemoveIndex(
            model_name='productcategory',
            name='idx_category_image_trgm',
        ),
    ]
