# Generated by Django 5.1.6 on 2025-11-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0052_alter_favourites_favourite_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'KG'), ('l', 'L'), ('sm', 'SM'), ('pcs', 'PCS'), ('m', 'M'), ('g', 'G')], default='pcs'),
        ),
    ]
