# Generated by Django 5.1.6 on 2025-11-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0053_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'KG'), ('l', 'L'), ('sm', 'SM'), ('pcs', 'PCS'), ('m', 'M'), ('g', 'G'), ('pkg', 'PKG')], default='pcs'),
        ),
    ]
