# Generated by Django 5.1.6 on 2025-11-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0054_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'KG'), ('l', 'L'), ('sm', 'SM'), ('pcs', 'PCS'), ('m', 'M'), ('g', 'G'), ('pkg', 'PKG'), ('set', 'SET')], default='pcs'),
        ),
    ]
