# Generated by Django 5.1.6 on 2026-04-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0058_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='hold_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
