# Generated by Django 5.1.6 on 2026-04-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_remove_fcmtoken_status'),
        ('base', '0019_deletebutton'),
        ('service', '0059_alter_order_hold_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['product'], name='idx_comment_product'),
        ),
        migrations.AddIndex(
            model_name='favourites',
            index=models.Index(fields=['customer', 'product'], name='idx_fav_cust_prod'),
        ),
        migrations.AddIndex(
            model_name='favourites',
            index=models.Index(fields=['favourite_token'], name='idx_fav_token'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'status'], name='idx_order_cust_status'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='idx_product_is_active'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='idx_product_brand'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_item_category'], name='idx_product_item_cat'),
        ),
    ]
