# Generated by Django 5.1.6 on 2026-04-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0060_comment_idx_comment_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ofd_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на чек'),
        ),
    ]
