# Generated by Django 5.1.6 on 2026-05-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0061_order_ofd_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Collecting'), (2, 'Delivering'), (3, 'Completed'), (4, 'Canceled')], default=0, verbose_name='Статус'),
        ),
    ]
