# Generated by Django 5.2.6 on 2026-06-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0062_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategory",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="name_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="name_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Название"),
        ),
    ]
