# Generated by Django 5.2.6 on 2026-06-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0063_alter_productcategory_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_type",
            field=models.IntegerField(
                choices=[(0, "Delivery"), (1, "Pickup")],
                default=0,
                verbose_name="Тип доставки",
            ),
        ),
    ]
