# Generated by Django 5.2.6 on 2026-06-24 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0064_order_delivery_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariantGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название группы"),
                ),
                (
                    "name_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Название группы"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Название группы"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Название группы"
                    ),
                ),
                (
                    "display_type",
                    models.CharField(
                        choices=[("text", "Text"), ("image", "Image")],
                        default="text",
                        max_length=10,
                        verbose_name="Тип отображения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа вариантов",
                "verbose_name_plural": "Группы вариантов",
            },
        ),
        migrations.CreateModel(
            name="ProductVariantItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "display_value",
                    models.CharField(max_length=255, verbose_name="Значение (текст)"),
                ),
                (
                    "display_value_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Значение (текст)"
                    ),
                ),
                (
                    "display_value_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Значение (текст)"
                    ),
                ),
                (
                    "display_value_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Значение (текст)"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="service.productvariantgroup",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant_items",
                        to="service.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент варианта",
                "verbose_name_plural": "Элементы вариантов",
                "ordering": ("created_at",),
                "unique_together": {("group", "product")},
            },
        ),
    ]
