# Generated by Django 5.1.6 on 2026-07-01 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0065_productvariantgroup_productvariantitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="guid",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="GUID из 1С",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Штрихкод"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="filter_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="product",
            name="guid",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="GUID из 1С",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="vendor_code",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Артикул"
            ),
        ),
        migrations.CreateModel(
            name="ProductItemCategoryFilterSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=100, verbose_name="Ключ (slug)")),
                (
                    "source_name_ru",
                    models.CharField(max_length=150, verbose_name="Название в 1С"),
                ),
                ("label", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "label_uz",
                    models.CharField(
                        max_length=150, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "label_ru",
                    models.CharField(
                        max_length=150, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "label_en",
                    models.CharField(
                        max_length=150, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("checkbox", "Multi-select"),
                            ("radio", "Single select"),
                            ("range", "Range slider"),
                        ],
                        default="checkbox",
                        max_length=20,
                        verbose_name="Тип фильтра",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Единица измерения"
                    ),
                ),
                ("position", models.IntegerField(default=0, verbose_name="Позиция")),
                (
                    "is_filterable",
                    models.BooleanField(default=True, verbose_name="Фильтруемый"),
                ),
                (
                    "type_locked",
                    models.BooleanField(default=False, verbose_name="Тип зафиксирован"),
                ),
                (
                    "item_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filter_schemas",
                        to="service.productitemcategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Схема фильтра категории",
                "verbose_name_plural": "Схемы фильтров категорий",
                "ordering": ("position",),
                "unique_together": {("item_category", "key")},
            },
        ),
        migrations.CreateModel(
            name="ProductFilterNumericValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.FloatField(verbose_name="Значение")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="numeric_filter_values",
                        to="service.product",
                        verbose_name="Продукт",
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="service.productitemcategoryfilterschema",
                        verbose_name="Схема фильтра",
                    ),
                ),
            ],
            options={
                "verbose_name": "Числовое значение фильтра",
                "verbose_name_plural": "Числовые значения фильтров",
            },
        ),
        migrations.DeleteModel(
            name="CategoryAttribute",
        ),
        migrations.DeleteModel(
            name="CategoryAttributeValue",
        ),
        migrations.DeleteModel(
            name="ProductAttributeValue",
        ),
        migrations.AddIndex(
            model_name="productfilternumericvalue",
            index=models.Index(
                fields=["schema", "value"], name="idx_num_filt_schema_val"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productfilternumericvalue",
            unique_together={("product", "schema")},
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_product_filter_data_gin "
            "ON service_product "
            "USING GIN (filter_data jsonb_path_ops)",
            reverse_sql="DROP INDEX IF EXISTS idx_product_filter_data_gin",
        ),
    ]

