# Generated by Django 5.1.6 on 2026-07-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0066_remove_productattributevalue_attribute_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productitemcategoryfilterschema",
            name="show_as_chip",
            field=models.BooleanField(default=False, verbose_name="Показывать как чип"),
        ),
    ]
