# Generated by Django 5.1.6 on 2026-07-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0067_productitemcategoryfilterschema_show_as_chip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productitemcategoryfilterschema",
            name="key",
            field=models.SlugField(
                allow_unicode=True, max_length=100, verbose_name="Ключ (slug)"
            ),
        ),
    ]
