# Generated by Django 5.1.6 on 2026-07-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0068_alter_productitemcategoryfilterschema_key_allow_unicode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productitemcategoryfilterschema",
            name="show_as_chip",
        ),
        migrations.AddField(
            model_name="productitemcategoryfilterschema",
            name="is_quick_filter",
            field=models.BooleanField(
                default=False, verbose_name="Быстрый фильтр (чип)"
            ),
        ),
        migrations.AddField(
            model_name="productitemcategoryfilterschema",
            name="max_quick_filters",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Макс. кол-во быстрых фильтров"
            ),
        ),
    ]
