# Generated by Django 5.1.6 on 2026-07-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0069_replace_show_as_chip_with_is_quick_filter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategory",
            options={
                "ordering": ("position",),
                "verbose_name": "Категория продуктов",
                "verbose_name_plural": "Категории продуктов",
            },
        ),
        migrations.AddField(
            model_name="productcategory",
            name="position",
            field=models.IntegerField(default=0, verbose_name="Позиция"),
        ),
    ]
