# Generated by Django 5.1.6 on 2026-07-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0070_alter_productcategory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("cash", "Наличные"), ("card", "Карта")],
                max_length=10,
                null=True,
                verbose_name="Способ оплаты при получении",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Click"),
                    (2, "Payme"),
                    (3, "Uzum Bank"),
                    (4, "При получении"),
                ],
                null=True,
                verbose_name="Тип оплаты",
            ),
        ),
    ]
