# Generated by Django 5.1.6 on 2026-07-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0072_productunit"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="receiver_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Имя получателя"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="receiver_phone",
            field=models.CharField(
                blank=True, max_length=14, null=True, verbose_name="Телефон получателя"
            ),
        ),
    ]
