# Generated by Django 5.1.6 on 2026-07-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0073_order_receiver_name_order_receiver_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="saved_price",
            field=models.FloatField(default=0.0, verbose_name="Сэкономленная сумма"),
        ),
    ]
