# Generated by Django 5.1.6 on 2026-07-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0074_order_saved_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="products_total_price",
            field=models.FloatField(
                default=0.0, verbose_name="Общая стоимость продуктов"
            ),
        ),
    ]
