# Generated by Django 5.1.6 on 2026-08-05 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0021_marketbranch"),
        ("service", "0078_yandex_delivery_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pickup_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.marketbranch",
                verbose_name="Филиал самовывоза",
            ),
        ),
    ]
