# Generated by Django 5.1.6 on 2025-03-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='')),
                ('phone_number', models.CharField(max_length=14, unique=True, verbose_name='')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='')),
                ('password', models.CharField(max_length=30, verbose_name='')),
                ('login_time', models.DateTimeField(blank=True, null=True, verbose_name='')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
    ]
