# Generated by Django 5.1.6 on 2025-04-14 09:45

import authorization.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='Полное имя')),
                ('phone_number', models.CharField(max_length=14, validators=[authorization.utils.validate_number], verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('password', models.CharField(verbose_name='Пароль')),
                ('verified', models.BooleanField(default=False, verbose_name='Подтвержден')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='FcmToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fcm_token', models.CharField(max_length=300, verbose_name='Фсм Токен')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Фсм Токен',
                'verbose_name_plural': 'Фсм Токены',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resend', models.BooleanField(default=False, verbose_name='Переотправить')),
                ('otp_code', models.IntegerField(verbose_name='ОТП код')),
                ('otp_key', models.CharField(default=uuid.uuid4, editable=False, max_length=250, unique=True, verbose_name='ОТП ключ')),
                ('count_attempts', models.IntegerField(default=0, verbose_name='Количество попыток')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает в')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'ОТП',
                'verbose_name_plural': 'ОТП',
            },
        ),
    ]
