# Generated by Django 5.1.6 on 2025-04-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='customer',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название локации'),
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Долгота'),
        ),
    ]
