# Generated by Django 5.1.6 on 2025-04-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_remove_customer_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddresses',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='customeraddresses',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='Долгота'),
        ),
    ]
