# Generated by Django 5.1.6 on 2025-04-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_alter_customeraddresses_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddresses',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
    ]
