# Generated by Django 5.1.6 on 2026-07-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0009_alter_customer_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("prorab", "Prorab")],
                default="user",
                max_length=20,
                verbose_name="Роль",
            ),
        ),
    ]
