# Generated by Django 5.1.6 on 2025-04-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_promocodes_delete_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodes',
            name='expires_at',
            field=models.DateField(blank=True, null=True, verbose_name='Истекает в'),
        ),
    ]
