# Generated by Django 5.1.6 on 2025-04-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_news_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocodes',
            name='expires_at',
            field=models.DateField(verbose_name='Истекает в'),
        ),
    ]
