# Generated by Django 5.1.6 on 2025-04-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_promocodes_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodes',
            name='code',
            field=models.CharField(default='something', max_length=15, unique=True, verbose_name='Код'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promocodes',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
