# Generated by Django 5.1.6 on 2025-04-30 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_customeraddresses_is_default'),
        ('base', '0009_promocodes_code_alter_promocodes_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodes',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authorization.customer', verbose_name='Клиент'),
            preserve_default=False,
        ),
    ]
