# Generated by Django 5.1.6 on 2025-05-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_banner_link_remove_banner_short_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.AddField(
            model_name='banner',
            name='desktop_image',
            field=models.ImageField(default='', upload_to='banner/desktop/', verbose_name='Компютерное изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='banner/mobile/', verbose_name='Телефонное изображение'),
        ),
    ]
