# Generated by Django 5.1.6 on 2025-05-14 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_passwordresettoken'),
        ('base', '0014_alter_banner_content_type_alter_banner_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Токен чата'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authorization.customer', verbose_name='Клиент'),
        ),
    ]
