# Generated by Django 5.1.6 on 2025-05-14 02:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_chat_session_alter_chat_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='session',
        ),
        migrations.AddField(
            model_name='chat',
            name='session_token',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=250, unique=True),
        ),
    ]
