# Generated by Django 5.1.6 on 2025-05-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_chat_session_chat_session_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='session_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
