# Generated by Django 5.1.6 on 2025-05-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_aboutus_description_en_aboutus_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='chat/', verbose_name='Изображение'),
        ),
    ]
