# Generated by Django 5.1.6 on 2025-05-31 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_messages_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='file',
            new_name='image',
        ),
    ]
