# Generated by Django 5.1.6 on 2025-12-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_file_messages_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=True, verbose_name='Удалено')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
