# Generated by Django 5.1.6 on 2025-05-14 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_chat_session_token_chat_cart_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='cart_token',
            new_name='session_token',
        ),
    ]
