# Generated by Django 5.1.6 on 2025-05-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_rename_cart_token_chat_session_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='session_token',
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Токен чата'),
        ),
    ]
