# Generated by Django 5.1.6 on 2026-08-05 09:48

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0020_baseinformation"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "name_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название локации",
                    ),
                ),
                (
                    "location_name_uz",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название локации",
                    ),
                ),
                (
                    "location_name_ru",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название локации",
                    ),
                ),
                (
                    "location_name_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название локации",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Адрес"
                    ),
                ),
                (
                    "branch_type",
                    models.IntegerField(
                        choices=[(0, "Showroom"), (1, "Market")],
                        default=1,
                        verbose_name="Тип филиала",
                    ),
                ),
                ("latitude", models.FloatField(verbose_name="Широта")),
                ("longitude", models.FloatField(verbose_name="Долгота")),
                (
                    "working_hours",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Рабочее время",
                    ),
                ),
                (
                    "description",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="Описание"
                    ),
                ),
                (
                    "description_uz",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "description_ru",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "description_en",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="branch/image/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("position", models.IntegerField(default=0, verbose_name="Позиция")),
            ],
            options={
                "verbose_name": "Филиал",
                "verbose_name_plural": "Филиалы",
                "ordering": ("position",),
            },
        ),
    ]
