# Generated by Django 5.1.6 on 2026-04-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_customercard_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customercard',
            options={'ordering': ['-is_default', '-created_at']},
        ),
        migrations.AddField(
            model_name='customercard',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
