# Generated by Django 5.1.6 on 2025-04-18 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_customer_latitude_customer_location_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='longitude',
        ),
        migrations.CreateModel(
            name='CustomerAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('location_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название локации')),
                ('latitude', models.CharField(blank=True, max_length=100, null=True, verbose_name='Широта')),
                ('longitude', models.CharField(blank=True, max_length=100, null=True, verbose_name='Долгота')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Адрес клиента',
                'verbose_name_plural': 'Адрес клиентов',
            },
        ),
    ]
