# Generated by Django 5.1.6 on 2025-05-31 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmtoken',
            name='device_id',
            field=models.CharField(default='', max_length=300, verbose_name='ID устройства'),
            preserve_default=False,
        ),
    ]
