# Generated by Django 5.1.6 on 2025-05-31 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_fcmtoken_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcmtoken',
            name='status',
        ),
    ]
