# Generated by Django 5.1.6 on 2026-07-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0008_remove_fcmtoken_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Электронная почта"
            ),
        ),
    ]
