# Generated by Django 5.1.6 on 2026-09-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0010_customer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, null=True, verbose_name='Пароль'),
        ),
    ]
