# Generated by Django 5.1.6 on 2026-09-24 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0011_alter_customer_full_name_alter_customer_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=14, unique=True, verbose_name='Номер телефона')),
                ('chat_id', models.BigIntegerField(verbose_name='Chat ID')),
                ('telegram_user_id', models.BigIntegerField(verbose_name='Telegram user ID')),
                ('username', models.CharField(blank=True, default='', max_length=64, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, default='', max_length=128, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Telegram привязка',
                'verbose_name_plural': 'Telegram привязки',
            },
        ),
        migrations.AddField(
            model_name='otp',
            name='channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('telegram', 'Telegram')], default='sms', max_length=20, verbose_name='Канал'),
        ),
        migrations.CreateModel(
            name='TelegramLinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Токен')),
                ('chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='Chat ID')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает в')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.customer', verbose_name='Клиент')),
                ('otp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authorization.otp', verbose_name='ОТП')),
            ],
            options={
                'verbose_name': 'Telegram токен привязки',
                'verbose_name_plural': 'Telegram токены привязки',
            },
        ),
    ]
