# Generated by Django 5.2.17 on 2026-09-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0012_telegram_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_blocked',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Заблокирован'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_login',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Последний вход'),
        ),
    ]
