# Generated by Django 5.2.17 on 2026-09-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0013_customer_block_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='customer/avatar/', verbose_name='Фото профиля'),
        ),
    ]
