# Generated by Django 5.2.17 on 2026-10-08 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_profiles(apps, schema_editor):
    """Existing dashboard admins (is_staff users) get a profile."""
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    StaffProfile = apps.get_model("authorization", "StaffProfile")
    StaffProfile.objects.bulk_create([
        StaffProfile(user=user, full_name=f"{user.first_name} {user.last_name}".strip() or user.username)
        for user in User.objects.filter(is_staff=True, staff_profile__isnull=True)
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0014_customer_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Ф.И.О.')),
                ('position', models.CharField(blank=True, default='', max_length=150, verbose_name='Должность')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='Сменить пароль при первом входе')),
                ('failed_login_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Неверные попытки входа')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.RunPython(create_profiles, migrations.RunPython.noop),
    ]
